import { 
  FileText, 
  LayoutDashboard, 
  BarChart3, 
  Inbox, 
  LayoutTemplate, 
  Puzzle, 
  Users, 
  CreditCard, 
  Settings,
  Plus,
  Search,
  Bell,
  ChevronDown,
  MoreHorizontal,
  Eye,
  Copy,
  Archive,
  Trash2,
  Edit,
  ExternalLink,
  Check,
  X,
  Calendar,
  Clock,
  Mail,
  Phone,
  Type,
  Hash,
  AlignLeft,
  ListFilter,
  CheckSquare,
  Circle,
  Star,
  Upload,
  PenTool,
  MapPin,
  Minus,
  GripVertical,
  ArrowRight,
  ArrowLeft,
  TrendingUp,
  TrendingDown,
  Globe,
  Smartphone,
  Monitor,
  Download,
  Filter,
  SortAsc,
  LogOut,
  User,
  Shield,
  Key,
  Palette,
  BellRing,
  Lock,
  RefreshCw,
  Zap,
  Link,
  Webhook,
  Code,
  Moon,
  Sun,
  Menu,
  ChevronRight,
  Home,
  PieChart,
  Activity,
  Target,
  Layers,
  Send,
  MessageSquare,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Loader2,
  ArrowUpRight,
  Building2,
  Briefcase,
  GraduationCap,
  Heart,
  ClipboardList,
  UserPlus,
  FileCheck,
  Megaphone,
  Sparkles,
  Play,
  Twitter,
  Github,
  Linkedin
} from "lucide-react"

export const Icons = {
  // Navigation
  dashboard: LayoutDashboard,
  forms: FileText,
  responses: Inbox,
  analytics: BarChart3,
  templates: LayoutTemplate,
  integrations: Puzzle,
  team: Users,
  billing: CreditCard,
  settings: Settings,
  home: Home,
  
  // Actions
  add: Plus,
  search: Search,
  bell: Bell,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  more: MoreHorizontal,
  view: Eye,
  copy: Copy,
  archive: Archive,
  delete: Trash2,
  edit: Edit,
  external: ExternalLink,
  check: Check,
  close: X,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  download: Download,
  filter: Filter,
  sort: SortAsc,
  logout: LogOut,
  menu: Menu,
  refresh: RefreshCw,
  send: Send,
  
  // Form Fields
  text: Type,
  number: Hash,
  email: Mail,
  phone: Phone,
  textarea: AlignLeft,
  dropdown: ListFilter,
  checkbox: CheckSquare,
  radio: Circle,
  date: Calendar,
  time: Clock,
  rating: Star,
  upload: Upload,
  signature: PenTool,
  address: MapPin,
  divider: Minus,
  grip: GripVertical,
  
  // Analytics
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  globe: Globe,
  smartphone: Smartphone,
  monitor: Monitor,
  pieChart: PieChart,
  activity: Activity,
  target: Target,
  
  // User
  user: User,
  userPlus: UserPlus,
  shield: Shield,
  key: Key,
  lock: Lock,
  
  // Settings
  palette: Palette,
  bellRing: BellRing,
  
  // Integrations
  zap: Zap,
  link: Link,
  webhook: Webhook,
  code: Code,
  
  // Theme
  moon: Moon,
  sun: Sun,
  
  // Status
  help: HelpCircle,
  info: Info,
  warning: AlertCircle,
  success: CheckCircle,
  error: XCircle,
  loader: Loader2,
  
  // Templates
  building: Building2,
  briefcase: Briefcase,
  graduation: GraduationCap,
  heart: Heart,
  clipboard: ClipboardList,
  fileCheck: FileCheck,
  message: MessageSquare,
  megaphone: Megaphone,
  layers: Layers,
  
  // Landing page
  sparkles: Sparkles,
  play: Play,
  twitter: Twitter,
  github: Github,
  linkedin: Linkedin,
  integration: Puzzle,
}
